<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jin-PC" name="com.code.test.ibnmsConfig.AgListTest" tests="17" failures="0" timestamp="17 Aug 2014 14:54:24 GMT" time="427.996" errors="8">
  <testcase name="searchAG" time="4.840" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="searchAG" time="4.294" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="deployAG" time="41.190" classname="com.code.test.ibnmsConfig.AgListTest">
    <error type="java.lang.AssertionError" message="{用例描述=卸载agent, 操作类型=卸载, 期望值=未部署, 结束标记=结束, 用例编号=CASE4, 是否运行=是, 备注=, 主机名称_AG=seleniumIBMName1, 状态字段=部署状态} expected [未部署] but found [已部署]">
      <![CDATA[java.lang.AssertionError: {用例描述=卸载agent, 操作类型=卸载, 期望值=未部署, 结束标记=结束, 用例编号=CASE4, 是否运行=是, 备注=, 主机名称_AG=seleniumIBMName1, 状态字段=部署状态} expected [未部署] but found [已部署]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.AgListTest.deployAG(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployAG -->
  <testcase name="deployAG" time="42.363" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="searchAG" time="6.492" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="deployAG" time="27.908" classname="com.code.test.ibnmsConfig.AgListTest">
    <error type="java.lang.AssertionError" message="{用例描述=部署可用agent, 操作类型=部署, 期望值=已部署, 结束标记=结束, 用例编号=CASE5, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=部署状态} expected [已部署] but found [未部署]">
      <![CDATA[java.lang.AssertionError: {用例描述=部署可用agent, 操作类型=部署, 期望值=已部署, 结束标记=结束, 用例编号=CASE5, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=部署状态} expected [已部署] but found [未部署]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.AgListTest.deployAG(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployAG -->
  <testcase name="deployAG" time="28.122" classname="com.code.test.ibnmsConfig.AgListTest">
    <error type="java.lang.AssertionError" message="{用例描述=部署agent, 操作类型=部署, 期望值=已部署, 结束标记=结束, 用例编号=CASE1, 是否运行=是, 备注=, 主机名称_AG=seleniumIBMName1, 状态字段=部署状态} expected [已部署] but found [未部署]">
      <![CDATA[java.lang.AssertionError: {用例描述=部署agent, 操作类型=部署, 期望值=已部署, 结束标记=结束, 用例编号=CASE1, 是否运行=是, 备注=, 主机名称_AG=seleniumIBMName1, 状态字段=部署状态} expected [已部署] but found [未部署]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.AgListTest.deployAG(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployAG -->
  <testcase name="searchAG" time="25.288" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="deployAG" time="23.303" classname="com.code.test.ibnmsConfig.AgListTest">
    <error type="java.lang.AssertionError" message="{用例描述=卸载可用agent, 操作类型=卸载, 期望值=未部署, 结束标记=结束, 用例编号=CASE8, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=部署状态} expected [未部署] but found [已部署]">
      <![CDATA[java.lang.AssertionError: {用例描述=卸载可用agent, 操作类型=卸载, 期望值=未部署, 结束标记=结束, 用例编号=CASE8, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=部署状态} expected [未部署] but found [已部署]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.AgListTest.deployAG(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployAG -->
  <testcase name="deployAG" time="22.280" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="operateAG" time="18.523" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="operateAG" time="40.242" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="deployAG" time="27.281" classname="com.code.test.ibnmsConfig.AgListTest">
    <error type="java.lang.AssertionError" message="{用例描述=部署可用agent, 操作类型=部署, 期望值=已部署, 结束标记=结束, 用例编号=CASE5, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=部署状态} expected [已部署] but found [未部署]">
      <![CDATA[java.lang.AssertionError: {用例描述=部署可用agent, 操作类型=部署, 期望值=已部署, 结束标记=结束, 用例编号=CASE5, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=部署状态} expected [已部署] but found [未部署]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.AgListTest.deployAG(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployAG -->
  <testcase name="operateAG" time="36.770" classname="com.code.test.ibnmsConfig.AgListTest"/>
  <testcase name="deployAG" time="19.896" classname="com.code.test.ibnmsConfig.AgListTest">
    <error type="java.lang.AssertionError" message="{用例描述=启动可用agent, 操作类型=启动, 期望值=运行中, 结束标记=结束, 用例编号=CASE6, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=运行状态} expected [运行中] but found [已停止]">
      <![CDATA[java.lang.AssertionError: {用例描述=启动可用agent, 操作类型=启动, 期望值=运行中, 结束标记=结束, 用例编号=CASE6, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=运行状态} expected [运行中] but found [已停止]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.AgListTest.deployAG(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployAG -->
  <testcase name="deployAG" time="19.155" classname="com.code.test.ibnmsConfig.AgListTest">
    <error type="java.lang.AssertionError" message="{用例描述=启动可用agent, 操作类型=启动, 期望值=运行中, 结束标记=结束, 用例编号=CASE6, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=运行状态} expected [运行中] but found [已停止]">
      <![CDATA[java.lang.AssertionError: {用例描述=启动可用agent, 操作类型=启动, 期望值=运行中, 结束标记=结束, 用例编号=CASE6, 是否运行=是, 备注=, 主机名称_AG=31test_bnms, 状态字段=运行状态} expected [运行中] but found [已停止]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.AgListTest.deployAG(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployAG -->
  <testcase name="deployAG" time="40.049" classname="com.code.test.ibnmsConfig.AgListTest">
    <error type="java.lang.AssertionError" message="{用例描述=启动agent, 操作类型=启动, 期望值=运行中, 结束标记=结束, 用例编号=CASE2, 是否运行=是, 备注=, 主机名称_AG=seleniumIBMName1, 状态字段=运行状态} expected [运行中] but found [已停止]">
      <![CDATA[java.lang.AssertionError: {用例描述=启动agent, 操作类型=启动, 期望值=运行中, 结束标记=结束, 用例编号=CASE2, 是否运行=是, 备注=, 主机名称_AG=seleniumIBMName1, 状态字段=运行状态} expected [运行中] but found [已停止]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.AgListTest.deployAG(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployAG -->
</testsuite> <!-- com.code.test.ibnmsConfig.AgListTest -->
